#
# Module manifest for module 'SIORestToolkit'
#
# Generated by: Karsten Bott
#
# Generated on: 14.04.2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SIORestToolkit.psm1'

# Version number of this module.
ModuleVersion = '2.0.1.2'

# ID used to uniquely identify this module
GUID = 'd3449f6d-c1e3-4873-87a3-2541628cc5bc'

# Author of this module
Author = 'Karsten Bott'

# Company or vendor of this module
CompanyName = 'EMC²'

# Copyright statement for this module
Copyright = '(c) 2016 Karsten Bott. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module vor EMC² ScaleIO 2.0 Rest API'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'
Tags = 'ScaleIO','Rest','API','EMC','DELL'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
'.\types\siovolume.psm1',
'.\types\siouser.psm1',
'.\types\sioalert.psm1',
'.\types\siolisttypes.psm1',
'.\types\SIOAlert.psm1',
'.\types\SIOVtree.psm1',
'.\actions\SIOmdm.psm1',
'.\actions\SIODevices.psm1',
'.\actions\SIOsdc.psm1',
'.\actions\SIOsds.psm1',
'.\actions\SIOvolume.psm1',
'.\actions\SIOSnapshot.psm1',
'.\actions\SIOProtectionDomain.psm1',
'.\errors\SIOerrors.psm1',
'.\gateway\SIOgateway.psm1',
'.\utils\utils.psm1'
)

# Functions to export from this module
FunctionsToExport = '*SIO*'

# Cmdlets to export from this module
CmdletsToExport = '*SIO*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/bottkars/SIORestToolkit'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

